### PR TITLE
Modify LICENSE.md to actually be in markdown.

### PR DESCRIPTION
**Pull request by robinlinden**
Replaces #29 
License downloaded from ~https://www.gnu.org/licenses/agpl-3.0.en.html~ https://raw.githubusercontent.com/IQAndreas/markdown-licenses/master/gnu-agpl-v3.0.md
Using the license from IQAndreas' repo as it's prettier, has the same information, and uses semantically correct markup.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/38)

### CODE REVIEW

**Comment by iphydf** [comment]
Where did you get this? I've been using https://raw.githubusercontent.com/IQAndreas/markdown-licenses/master/gnu-agpl-v3.0.md in all other repos.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaE9mLwfU1CRvLoUeSh:bgl7hiw)*

**Comment by robinlinden** [comment]
There's a link to https://www.gnu.org/licenses/agpl-3.0.md on the https://www.gnu.org/licenses/agpl-3.0.en.html page. It's also available in HTML, LaTeX, and a ton of other formats.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaEA95OW7BhTMiIpApo:b41ab3c)*

**Comment by iphydf** [comment]
:lgtm_strong: it's not as pretty, but let's use the official gnu one indeed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaEA_zbSU034clGBEIr:bdgquhp)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[LICENSE.md, line 6 at r1](https://reviewable.io:443/reviews/toktok/website/38#-KaEAr_aFG9El48b4rEs:-KaEAr_aFG9El48b4rEt:b2f5vrl) ([raw file](https://github.com/toktok/website/blob/1ed2e9f37875db48a95b3333ad5fa8612d260967/LICENSE.md#L6)):*
> ```Markdown
> 
> Copyright (C) 2007 Free Software Foundation, Inc.
> <http://fsf.org/>
> ```

This is an example of something I think is prettier on the inofficial one: https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-agpl-v3.0.md

Also the ©, and a few other things. But I guess using the official one is better still.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38)*

**Comment by robinlinden** [comment]
I agree that it's not as pretty. IQAndreas' version is also more semantically correct. The official version starts with a <h3> instead of a <h1> for example. I sort of want to switch to his version now that I know about it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaEAd-_-rCV5Xd1WX3x:bm7jxry)*

**Comment by robinlinden** [comment]
Ugh. ^ should say: I agree that it's not as pretty. IQAndreas' version is also more semantically correct. The official version starts with a `<h1>` instead of a `<h3>` for example. I sort of want to switch to his version now that I know about it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaEBiP_G8TBvyfbgOzg:brucj0a)*

**Comment by robinlinden** [comment]
Switched from the GNU markup version to IQAndreas' markup version.

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38)*

**Comment by subliun** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38)*

**Comment by subliun** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38#-:-KaIK79zq4_fhkZE-PY4:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/38)*

**Pull request merged**
