### PR TITLE
Adopt the tox.chat design so we look more integrated.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/89)

### CODE REVIEW

**Comment by SkyzohKey** [comment]
Tables are broken for now.

**Comment by iphydf** [comment]
Yep. Someone fix it? :)

**Comment by SkyzohKey** [comment]
Will do :)

**Comment by SkyzohKey** [comment]
@iphydf Would something like that be nice for u ? http://beta.tox.chat/blog/post/3/tox-chat-logs-standard#conventions--variables

**Comment by iphydf** [comment]
Yes, I like it :).

**Pull request merged**
