### PR TITLE
Add linkchecker and markdown linter.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/16)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.md-style.rb, line 1 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-RIBi-okZAiCXlEie:-Ka-RIBi-okZAiCXlEif:bqspegq) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/.md-style.rb#L1)):*
> ```Ruby
> all
> ```

Can we sort the rules in ascending order? Regardless of whether they're excluded or configured. Makes going through them together with https://github.com/mivok/markdownlint/blob/master/docs/RULES.md easier.

---

*[toktok/spec.md, line 8 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-V0g6Gey4NTA7GRMa:-Ka-V0g6Gey4NTA7GRMb:b-t2ufii) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/spec.md#L8)):*
> ```Markdown
> ---
> 
> *   The line below will tell kramdown to generate the ToC on this line.
> ```

You can replace `*` with `-` so it matches the other lists. It only has to be a list marker. You can even make it `1.` for a numbered list.

---

*[toktok/design/testing.md, line 14 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-VXwq2e4xcHgRsXew:-Ka-VXwrWJL9oVP6783T:b-ci71fd) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L14)):*
> ```Markdown
> validate any [Tox Core Protocol](https://toktok.github.io/spec)
> implementation, including the C reference implementation
> [libtoxcore](https://github.com/toktok/c-toxcore).  We aim to create an
> ```

Why 2 spaces here?

---

*[toktok/design/testing.md, line 82 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-VdLIrZAVn1W93d5t:-Ka-VdLJQYrIY_FsRTnX:b-ci71fd) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L82)):*
> ```Markdown
> remain untested and must be tested in the implementation-specific test suite.
> This includes networking, but also any functionality that relies on
> randomness.  Notably this includes generating key pairs and nonces. Tests that
> ```

Why 2 spaces here?

---

*[toktok/design/testing.md, line 105 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-Vhf5J1s5dErf69qK:-Ka-Vhf6zf2JTXW7fz_W:bcbq0kn) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L105)):*
> ```Markdown
> 
> [Hspec](https://hspec.github.io/) will be used to write the test
> specification.  Every Haskell module `M` will have an associated `${M}Spec`
> ```

Why 2 spaces?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.md-style.rb, line 1 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-RIBi-okZAiCXlEie:-Ka-dAfsukAkoVSfXTcT:b-896fix) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/.md-style.rb#L1)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Can we sort the rules in ascending order? Regardless of whether they're excluded or configured. Makes going through them together with https://github.com/mivok/markdownlint/blob/master/docs/RULES.md easier.
</blockquote></details>

Done.

---

*[toktok/spec.md, line 8 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-V0g6Gey4NTA7GRMa:-Ka-dFob8-oQ-cmPn6in:b-896fix) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/spec.md#L8)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You can replace `*` with `-` so it matches the other lists. It only has to be a list marker. You can even make it `1.` for a numbered list.
</blockquote></details>

Done.

---

*[toktok/design/testing.md, line 14 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-VXwq2e4xcHgRsXew:-Ka-dHeAckrKU1HpO8Y3:b-l1pr87) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L14)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why 2 spaces here?
</blockquote></details>

Typesetting. No need though. Removed.

---

*[toktok/design/testing.md, line 82 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-VdLIrZAVn1W93d5t:-Ka-ddZMv4wBgXxSJyg1:b-896fix) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L82)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why 2 spaces here?
</blockquote></details>

Done.

---

*[toktok/design/testing.md, line 105 at r1](https://reviewable.io:443/reviews/toktok/website/16#-Ka-Vhf5J1s5dErf69qK:-Ka-deQkSdkcpF-ADi_x:b-896fix) ([raw file](https://github.com/toktok/website/blob/6c573b187a9af3a91129c1e4a218fee1236ff23d/toktok/design/testing.md#L105)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Why 2 spaces?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16)*

**Comment by iphydf** [comment]
Reviewed 8 of 13 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16#-:-Ka-jGhGGJEmoC2N9STY:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Reviewed 8 of 13 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/16#-:-Ka-jzbc325KiCL_DDzj:bg7igkv)*

**Pull request merged**
