### PR TITLE
Update integrations.md

### PR DESCRIPTION
**Pull request by 137x3w**
Adding Node.js addon

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/121)

### CODE REVIEW

**Comment by SkyzohKey** [comment]
Hi @w3x731 and thanks for the PR, could you move your binding to the bindings section in that same file please? :)

**Comment by iphydf** [comment]
The "JavaScript" one above it is also node.js. Can you standardise on one name?

**Comment by iphydf** [comment]
:lgtm_strong: I'll do it myself then.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/toktok/website/121#-:-LEWorGW-t-O_ILA7OvV:b6n6w9k)*

**Comment by 137x3w** [comment]
@iphydf Thanks

**Pull request merged**
