### PR TITLE
Add `Get started` page with some initial content

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/31)

### CODE REVIEW

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/index.md, line 34 at r1](https://reviewable.io:443/reviews/toktok/website/31#-Ka8qdut7f3_pyah5tVe:-Ka8qdut7f3_pyah5tVf:bp82dk6) ([raw file](https://github.com/toktok/website/blob/662cb62f20bd894ce82449417950b43ce4c20361/toktok/index.md#L34)):*
> ```Markdown
> # Get started
> 
> [Collection of resources for developers.](./get-started.html)
> ```

Any reason for `./`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/31)*

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toktok/index.md, line 34 at r1](https://reviewable.io:443/reviews/toktok/website/31#-Ka8qdut7f3_pyah5tVe:-Ka9X6aObOX7uEQV5hl5:b-pyrbqy) ([raw file](https://github.com/toktok/website/blob/662cb62f20bd894ce82449417950b43ce4c20361/toktok/index.md#L34)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Any reason for `./`?
</blockquote></details>

No. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/31)*

**Comment by linux-modder** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/31)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/31#-:-KaA-7y0TkpHN1wZLHQG:b-jbsf8z)*

**Comment by linux-modder** [comment]
Looks good. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/31#-:-KaN2Mz8HxJSEeXxyqeg:b3kn5fu)*

**Pull request merged**
