### PR TITLE
Make all headings subheadings of the title of the page.

### PR DESCRIPTION
**Pull request by robinlinden**
This is more accessible, semantically correct, and better for SEO.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes

~~We should also in the future make sure that .md documents with a title specified in the front-matter start their headings at `##`.~~

After discussion on IRC, we will now automatically increment headings by 1 instead of requiring the contributor to fix their markdown.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/26)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26#-:-Ka38ht50gy1pc6dytPE:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26)*

**Comment by iphydf** [comment]
Reviewed 1 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26)*

**Comment by cebe** [comment]
Reviewed 1 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26#-:-KaAxpCBSSsCwkSZOesN:b-jbsf8z)*

**Comment by iphydf** [comment]
@zetok this is missing your LGTM.
@robinlinden can you rebase this?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26#-:-KaCFWBUBPoDDJPug83H:bdcmviv)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 1 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26#-:-KaCISLCK74NVuL8cVHx:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 1 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/26)*

**Pull request merged**
