### PR TITLE
Add integrations page.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/79)

### CODE REVIEW

**Comment by SkyzohKey** [comment]
LGTM

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/79#-:-L3F5ME8xFHyDNwrF-27:b-jbsf8z)*

**Review by SkyzohKey — CHANGES_REQUESTED** [review]
+ I have found another client: https://github.com/pojoba02/Xotic
+ The one I'm currently working on: https://github.com/Tox-Client/client

Oh and you forgot another great Tox project !!
+ https://github.com/toxmail/toxmail

**Comment by iphydf** [comment]
@SkyzohKey can you add those? The idea is that everybody who writes some integrations or clients can add them. Feel free to add yours to the list (make sure the list stays sorted).

**Comment by SkyzohKey** [comment]
Yeah, I'll add that asap :)

**Pull request merged**
