### PR TITLE
Update links to Rust implementation

### PR DESCRIPTION
**Pull request by kpp**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/119)

### CODE REVIEW

**Comment by kpp** [comment]
@iphydf Hello?

**Comment by sudden6** [comment]
cc @robinlinden

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/toktok/website/119#-:-L9AW1Vp8bN72rJIa8uO:b-jbsf8z)*

**Comment by iphydf** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

Also, remove the "/" at the end of "tox/" in links.

**Comment by kpp** [comment]
Done

**Pull request merged**
