### PR TITLE
Change "design documents" to "documents".

### PR DESCRIPTION
**Pull request by zoff99**
add ToxCon documents to website

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/136)

### CODE REVIEW

**Review by iphydf — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/toktok/website/136#-:-LPNFjUGBKfstYhyyUwQ:b-jbsf8z)* status: 0 of 1 approvals obtained

**Review by robinlinden — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/website/136)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @zoff99)

*[a discussion](https://reviewable.io/reviews/toktok/website/136#-LPSJarr9JeSadL3a8PP:-LPSJarr9JeSadL3a8PQ:b-28gpr0) (no related file):*
Since you're generating a file called documents.html, you should probably rename the markdown file it's generated from to documents.md.

---

**Comment by zoff99** [comment]
@robinlinden will that break stuff if i rename the .md file?

**Review by zoff99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/website/136)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @robinlinden)

*[a discussion](https://reviewable.io/reviews/toktok/website/136#-LPSJarr9JeSadL3a8PP:-LPUx7fs1u-tOCcjBkh5:b-896fix) (no related file):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Since you're generating a file called documents.html, you should probably rename the markdown file it's generated from to documents.md.
</blockquote></details>

Done.

---

**Comment by robinlinden** [comment]
@zoff99 If anything was going to break, it would have been the change of the actual url. :P I had a quick look and didn't see anything on this website that pointed to `/designs.html`, so it should be fine.

**Comment by zoff99** [comment]
@robinlinden ok. give lgtm please

**Review by robinlinden — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/toktok/website/136)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained

**Pull request merged**
