### PR TITLE
Change url from toktok.github.io to toktok.ltd.

### PR DESCRIPTION
**Pull request by robinlinden**
This change only affects our canonical urls.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/44)

### CODE REVIEW

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44#-:-KaI7s3jfj3aQSpcgICw:b-jbsf8z)*

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toktok/_config.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/website/44#-KaI81Z46Fu6mm9LzRuI:-KaI81Z46Fu6mm9LzRuJ:bf52w4f) ([raw file](https://github.com/toktok/website/blob/5b351ce5632c58aa0a7c0c564e7ee1f470bb107d/toktok/_config.yml#L3)):*
> ```YAML
> title: The TokTok Project
> baseurl: "" # the subpath of your site, e.g. /blog
> url: "http://toktok.ltd" # the base hostname & protocol for your site
> ```

is it possible to have https with custom domain? via letsencrypt or similar?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44#-:-KaI8QTbt4Hac69VQ3u6:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toktok/_config.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/website/44#-KaI81Z46Fu6mm9LzRuI:-KaI9kamJIl4JgrymfjE:b-hdake1) ([raw file](https://github.com/toktok/website/blob/5b351ce5632c58aa0a7c0c564e7ee1f470bb107d/toktok/_config.yml#L3)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

is it possible to have https with custom domain? via letsencrypt or similar?
</blockquote></details>

I'm working on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toktok/_config.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/website/44#-KaI81Z46Fu6mm9LzRuI:-KaIAI9IY-bZbh12oqvM:b-sx4q4g) ([raw file](https://github.com/toktok/website/blob/5b351ce5632c58aa0a7c0c564e7ee1f470bb107d/toktok/_config.yml#L3)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I'm working on it.
</blockquote></details>

okay ,cool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by fcore117** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44#-:-KaLu0_VO8Gvzkya5jr4:bg7igkv)*

**Comment by Zer0-One** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44#-:-KaM8nodYHzIxPvmQK7_:bg7igkv)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[toktok/_config.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/website/44#-KaI81Z46Fu6mm9LzRuI:-KaPDRgjewBiR1nTWSGK:b-5msgsa) ([raw file](https://github.com/toktok/website/blob/5b351ce5632c58aa0a7c0c564e7ee1f470bb107d/toktok/_config.yml#L3)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

okay ,cool.
</blockquote></details>

We're https ready now. @robinlinden change it to https.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[toktok/_config.yml, line 3 at r1](https://reviewable.io:443/reviews/toktok/website/44#-KaI81Z46Fu6mm9LzRuI:-KaXBRzfBOYh5fYK5kdW:b-896fix) ([raw file](https://github.com/toktok/website/blob/5b351ce5632c58aa0a7c0c564e7ee1f470bb107d/toktok/_config.yml#L3)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

We're https ready now. @robinlinden change it to https.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/44)*

**Pull request merged**
