### PR TITLE
Add line break before "loading pull requests".

### PR DESCRIPTION
**Pull request by iphydf**
Currently it's directly following the "click on ..." paragraph.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/35)

### CODE REVIEW

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toktok/pulls.html, line 12 at r1](https://reviewable.io:443/reviews/toktok/website/35#-KaETZ4R9-HZb1OZae71:-KaETZ4R9-HZb1OZae72:b-tpybfs) ([raw file](https://github.com/toktok/website/blob/b243cd0719293628bc2b17c0061e774d274709f0/toktok/pulls.html#L12)):*
> ```HTML
> review. Click on the branch to see the pull request on GitHub.</p>
> 
> <div class="loading"><p>Loading Pull requests...</p></div>
> ```

no need to wrap the `<p>` in a `<div>`. we should put the class on the `<p>` instead and adjust the JS to remove that p element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toktok/static/js/pr-table.js, line 20 at r2](https://reviewable.io:443/reviews/toktok/website/35#-KaEk2n7kdIiVJ6AW2Ld:-KaEk2n7kdIiVJ6AW2Le:b-7rkcal) ([raw file](https://github.com/toktok/website/blob/158a58d99d35cabe90c62b0963a5dc26cbf4ebd2/toktok/static/js/pr-table.js#L20)):*
> ```JavaScript
>   .then(function(response) { return response.json(); })
>   .then(function(json) {
>     var loadingDiv = repoSection.querySelector("p.loading");
> ```

You could leave this as just `.loading` and we wouldn't have to touch the js if we feel like changing the tag again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35#-:-KaElD3WAuVZqQYVy1tp:b-jbsf8z)*

**Comment by cebe** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toktok/static/js/pr-table.js, line 20 at r2](https://reviewable.io:443/reviews/toktok/website/35#-KaEk2n7kdIiVJ6AW2Ld:-KaEpmFUwO5FCed6opAn:b-896fix) ([raw file](https://github.com/toktok/website/blob/158a58d99d35cabe90c62b0963a5dc26cbf4ebd2/toktok/static/js/pr-table.js#L20)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

You could leave this as just `.loading` and we wouldn't have to touch the js if we feel like changing the tag again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35)*

**Comment by cebe** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/pulls.html, line 12 at r1](https://reviewable.io:443/reviews/toktok/website/35#-KaETZ4R9-HZb1OZae71:-KaEz6kaZA6MQWT-8FCD:b-whxixv) ([raw file](https://github.com/toktok/website/blob/b243cd0719293628bc2b17c0061e774d274709f0/toktok/pulls.html#L12)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

no need to wrap the `<p>` in a `<div>`. we should put the class on the `<p>` instead and adjust the JS to remove that p element.
</blockquote></details>

Thanks for fixing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/35)*

**Pull request merged**
