### PR TITLE
Switch the pulls file over to using markdown.

### PR DESCRIPTION
**Pull request by robinlinden**
Markdown generation in this file wasn't working before since I had given it a .html extension instead of the .md I should have used.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/48)

### CODE REVIEW

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/48#-:-KaPGhK9OicjPieYf8R_:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/48)*

**Comment by cebe** [comment]
`make lint` seems unhappy about this:

```
$ make lint
mdl -w -s .md-style.rb toktok
toktok/pulls.md: Kramdown Warning: No link definition for link ID 'twemoji-2.2.3.min.js, pr-table.js' found on line 6
make: *** [lint] Error 2
```

seems it does not understand the meta data headers and thinks you are using a link here `[ ... ]` but forgot the parenthesis for the url.

**Comment by cebe** [comment]
according to its help message:

```
    -i, --[no-]ignore-front-matter   Ignore YAML front matter
```

adding `-i` to the mdl call should fix this.

**Comment by iphydf** [comment]
Easy fix: use yaml style arrays.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/48#-:-KaTK2CUne0SF90FOe0y:b-69hp15)*

**Comment by cebe** [comment]
@iphydf my fix seems better :)

**Comment by iphydf** [comment]
Agreed - if it works. @robinlinden try @cebe's fix first.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/48#-:-KaTKDWwGA1Dy8VkqUL-:bvakuob)*

**Pull request merged**
