### PR TITLE
Convert css to scss.

### PR DESCRIPTION
**Pull request by robinlinden**
It has a better syntax, more features, and is generally a lot nicer to work in than plain CSS.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/46)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46#-:-KaIRsI2N6SdpGv0nY40:b-jbsf8z)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46#-:-KaISh13i-X5e80Lq5_d:b-jbsf8z)*

**Comment by cebe** [comment]
Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46)*

**Comment by iphydf** [comment]
Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/46#-:-KaLX1YzPGgFfvnxuvPD:b-jbsf8z)*

**Pull request merged**
