### PR TITLE
Fix makefile dependencies on changelog and roadmap.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/40)

### CODE REVIEW

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 12 at r1](https://reviewable.io:443/reviews/toktok/website/40#-KaFqiDeyJQ68vlHS7yj:-KaFqiDftf4QhgyXShZz:b-9acx9t) ([raw file](https://github.com/toktok/website/blob/06e4695f2e8aface0056a3454932ba89ec32fb7f/Makefile#L12)):*
> ```Makefile
> # build the website with jekyll
> #
> toktok-site: $(shell which jekyll) $(shell find toktok -type f) emoij changelog roadmap spec
> ```

I intentionally avoided the site building depend on spec because we have pandoc as optional in the readme. I'm fine with this change but then the "optional" note should be removed in the README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 12 at r1](https://reviewable.io:443/reviews/toktok/website/40#-KaFqiDeyJQ68vlHS7yj:-KaHNy0xIqcAzOECZ4m3:b-cdgie0) ([raw file](https://github.com/toktok/website/blob/06e4695f2e8aface0056a3454932ba89ec32fb7f/Makefile#L12)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I intentionally avoided the site building depend on spec because we have pandoc as optional in the readme. I'm fine with this change but then the "optional" note should be removed in the README.
</blockquote></details>

Made it optional by checking if pandoc exists before executing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40#-:-KaHj2BaSNxn8NTjsCOb:b-jbsf8z)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40#-:-KaHxwLLD9Z-aTEMd6eH:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40)*

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/40)*

**Pull request merged**
