### PR TITLE
updated text file

### PR DESCRIPTION
**Pull request by Pratik-11**
hey nic to meet you
i m a new one here just staritng to do things
did some minor changes in yours too. :)

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/189)

### CODE REVIEW

**Comment by Pratik-11** [comment]
> [CLA assistant check](https://cla-assistant.io/TokTok/website?pullRequest=189)
> All committers have signed the CLA.

done now it will be counted>?

**Comment by Pratik-11** [comment]
Why posted it spam bro😐

**Comment by anthonybilinski** [comment]
Your account's two days old, you have 45 contributions in that time, you have multiple commits in "HacktoberFest2020" repos, this repo alone got about 40 PRs in one day all with very similar spam like this. I marked it as spam so that you don't get any credit for Hacktoberfest.

The change itself introduces multiple errors and doesn't fix anything. It's not just a trivial change, it's an actively bad change.

**Comment by Pratik-11** [comment]
I told you I m a new one I didn't know wht edits I can do and you just soaked it you may have considered it invalid.😭 Maybe now I can't participate in hacktoberfest cause I got a spam you didn't did it ri8
🥺

**Pull request closed without merging**
