### PR TITLE
Add note about lack of security audit.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/50)

### CODE REVIEW

**Comment by iphydf** [comment]
@zx2c4 does this note look reasonable?

I will work on a more detailed set of security advisories later. For now, this is all I had time for.

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toktok/index.md, line 33 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPwM4QoFVKE6_LqzpW:-KaPwM4R3oDvESexdnlp:b-c69jdz) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/index.md#L33)):*
> ```Markdown
> 
> Neither the Tox protocol nor the implementation have undergone peer review,
> and its exact security properties and network behaviour and not
> ```

"and not" -> "are not"

---

*[toktok/repos.md, line 8 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPwXI304U6ghMqaGxz:-KaPwXI304U6ghMqaGy-:b-8nvvgq) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/repos.md#L8)):*
> ```Markdown
> ---
> 
> You can file bugs against one of the TokTok projects on Github. Build status
> ```

"bug reports" instead of "bugs".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaPx2QvY5JwIexwmeXS:b-jbsf8z)*

**Comment by nicoonoclaste** [comment]
*[toktok/index.md, line 36 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPxexVcLDpwTBAGODw:-KaPxexWQJeASx5XqCZ9:b-hofs78) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/index.md#L36)):*
> ```Markdown
> well-understood, yet. We are actively working on improving that situation.
> Until said peer review, Tox is not recommended for use cases that require
> proven high assurance security.
> ```

“proven, high-assurance security”

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Comment by nicoonoclaste** [comment]
The move to `repos.md` ought to be a separate commit.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaPxongcqsYKBUevhl1:b-c684f6)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Comment by nicoonoclaste** [comment]
:lgtm_strong: assuming those two nitpicks are handled.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaPyCxDNuItmEXgNQTM:bk9uize)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaPynvRBRlTGnJEG-xU:b-jbsf8z)*

**Comment by cebe** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Comment by robinlinden** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Comment by cebe** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Comment by iphydf** [comment]
Please take another look. I have added an invitation to report security issues. It may not be strictly necessary as it should be implied.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[toktok/index.md, line 33 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPwM4QoFVKE6_LqzpW:-KaPyxMf34mAPq1laoIC:b-896fix) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/index.md#L33)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

"and not" -> "are not"
</blockquote></details>

Done.

---

*[toktok/index.md, line 36 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPxexVcLDpwTBAGODw:-KaPyxrJdANWJRUYezNN:b-896fix) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/index.md#L36)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary><blockquote>

“proven, high-assurance security”
</blockquote></details>

Done.

---

*[toktok/repos.md, line 8 at r1](https://reviewable.io:443/reviews/toktok/website/50#-KaPwXI304U6ghMqaGxz:-KaPz-FfCpSponHcxl3V:b-896fix) ([raw file](https://github.com/toktok/website/blob/3e963edec7dd32cb1afe4f626eec1cd991f5b70a/toktok/repos.md#L8)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

"bug reports" instead of "bugs".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaPz0w9BrIwJZTcY8Ht:b-2s81ta)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaQ7hiB5XBrvVXC7p9v:b-jbsf8z)*

**Comment by Zer0-One** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50#-:-KaQNhD3IUSvdkueUkxt:bg7igkv)*

**Comment by nicoonoclaste** [comment]
Reviewed 2 of 2 files at r2, 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/50)*

**Pull request merged**
