### PR TITLE
add jTox

### PR DESCRIPTION
**Pull request by almindor**
Adds jTox mobile client for SailfishOS devices.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/138)

### CODE REVIEW

**Comment by zoff99** [comment]
@almindor  what is the difference to this one: https://github.com/emmanuelduv/harbour-tox
?
can you add more info, so that people don't get confused please

**Comment by almindor** [comment]
It's a completely different project. I also don't know much about it except it seems both the other Jolla/Sailfish OS ones are 2 year old+ with no recent activity.

**Comment by almindor** [comment]
I created jTox from scratch. I completely missed Cyanide initially but since it didn't seem to get updated much and I got to almost parity with it I just continued my project. The other project didn't ever make it to the official store or openrepos so I didn't even know it existed.

As far as I can say jTox is the only actively developed SFOS client at this time.

**Review by robinlinden — CHANGES_REQUESTED** [review]
Can you move jTox down a bit so the list stays sorted in alphabetical order? :)

**Comment by almindor** [comment]
moved

**Comment by almindor** [comment]
Ping, do you guys need anything else?

**Review by robinlinden — APPROVED** [review]
No, sorry, I missed the update on this. :lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/toktok/website/138#-:-LRrH_0w7E4Ib84ZZbmU:bewqnwy)* status: 1 change requests, 0 of 1 approvals obtained

**Pull request merged**
