### PR TITLE
Refactor out pr-table js into its own file.

### PR DESCRIPTION
**Pull request by robinlinden**
Add easy way of properly including js.
Add folder for js content.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/27)

### CODE REVIEW

**Comment by iphydf** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27#-:-Ka3meLKpyq4vD3Grkb6:b-jbsf8z)*

**Comment by cebe** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/static/js/pr-table.js, line 67 at r1](https://reviewable.io:443/reviews/toktok/website/27#-Ka4fhIOssKff4TqQpN3:-Ka4fhIOssKff4TqQpN4:bpomhyv) ([raw file](https://github.com/toktok/website/blob/bb8134d27fd872358f6ccfff5b9aa7368e194652/toktok/static/js/pr-table.js#L67)):*
> ```JavaScript
>         twemoji.parse(prTable, {
>             callback: function(icon, options) {
>               return '{{ relative }}static/img/emoij/' + options.size + '/' + icon + '.png';
> ```

as per IRC, this does not work. `{{ relative }}` is not parsed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27)*

**Comment by robinlinden** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/static/js/pr-table.js, line 67 at r1](https://reviewable.io:443/reviews/toktok/website/27#-Ka4fhIOssKff4TqQpN3:-Ka7SzEYBELDkMttGtXc:b16k0ry) ([raw file](https://github.com/toktok/website/blob/bb8134d27fd872358f6ccfff5b9aa7368e194652/toktok/static/js/pr-table.js#L67)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

as per IRC, this does not work. `{{ relative }}` is not parsed.
</blockquote></details>

Done. Changed this to be done the way you suggested on IRC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27)*

**Comment by cebe** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27#-:-Ka7tmn5RwgjDHfljpLw:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/27)*

**Pull request merged**
