### PR TITLE
Moved travis commands into make file for local development

### PR DESCRIPTION
**Pull request by cebe**
This will allow using the same commands as run by travis via the
Makefile for local development.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/34)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 4 of 11 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBUoYEWsYjTnLlE5lj:-KaBUoYGNSgiI5P_oECS:br0m0zx) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L9)):*
> ```Markdown
> To work on the website you need the following things:
> 
> - Jekyll and mdl via ruby gems: `gem install jekyll mdl` (mdl is optinal, for linting the markdown)
> ```

s/optinal/optional

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBVM0F2wYDjIMK6B97:-KaBVM0F2wYDjIMK6B98:b-x02rcp) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L10)):*
> ```Markdown
> 
> - Jekyll and mdl via ruby gems: `gem install jekyll mdl` (mdl is optinal, for linting the markdown)
> - pandoc, e.g. via `apt-get install pandoc` or <http://pandoc.org/installing.html>
> ```

May want to include `cabal install pandoc` since cabal is included in the Haskell platform and basically the Haskell version of ruby gems.

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBdNyoRz_VKHz8i_a-:-KaBdNyqBUZByY9-De4f:b-codwwr) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L22)):*
> ```Markdown
> - `make spec`: download and parse the spec with pandoc (included in `all`)
> - `make lint`: run markdown linter `mdl`
> - `make check`: runs linkchecker
> ```

s/runs/run

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by iphydf** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 23 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaCH9jjtAO9faoiDcLq:-KaCH9jjtAO9faoiDcLr:b-6rq8qh) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/Makefile#L23)):*
> ```Makefile
> changelog: toktok/changelog/c-toxcore.md
> toktok/changelog/c-toxcore.md:
> 	cp $@.dist $@
> ```

Clearly c-toxcore.md depends on c-toxcore.md.dist. Please add this dependency. You can then use `$<` here.

Theoretically you could even do:
```make
toktok/%/c-toxcore.md: toktok/%/c-toxcore.md.dist
        cp $< $@
        curl https://git-critique.herokuapp.com/hello/$* >> $@
```

Up to you if you want to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 23 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaCH9jjtAO9faoiDcLq:-KaDbrwAr7GI1XeL5giP:b-896fix) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/Makefile#L23)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Clearly c-toxcore.md depends on c-toxcore.md.dist. Please add this dependency. You can then use `$<` here.

Theoretically you could even do:
```make
toktok/%/c-toxcore.md: toktok/%/c-toxcore.md.dist
        cp $< $@
        curl https://git-critique.herokuapp.com/hello/$* >> $@
```

Up to you if you want to do that.
</blockquote></details>

Done.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBUoYEWsYjTnLlE5lj:-KaDbvZcsPJ2z92tDXeK:b-896fix) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L9)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

s/optinal/optional
</blockquote></details>

Done.

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBVM0F2wYDjIMK6B97:-KaDbwbX2ztogb5s-37m:b-896fix) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L10)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

May want to include `cabal install pandoc` since cabal is included in the Haskell platform and basically the Haskell version of ruby gems.
</blockquote></details>

Done.

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBdNyoRz_VKHz8i_a-:-KaDbxLCprPAluY2jRYv:b-896fix) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L22)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

s/runs/run
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by iphydf** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBVM0F2wYDjIMK6B97:-KaDcsbMFdM8TX4bnMbG:bl3zfp7) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L10)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`cabal install pandoc` will take half an hour, while the apt-get version takes 1 minute. Perhaps note that we need at least version ..something.. (I don't actually know, but I know that 1.12 (Ubuntu trusty) works and 1.9 (Ubuntu precise) doesn't).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBVM0F2wYDjIMK6B97:-KaDkBChe1nf6rBDSktm:b-eh06wn) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L10)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`cabal install pandoc` will take half an hour, while the apt-get version takes 1 minute. Perhaps note that we need at least version ..something.. (I don't actually know, but I know that 1.12 (Ubuntu trusty) works and 1.9 (Ubuntu precise) doesn't).
</blockquote></details>

so better remove it again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34#-:-KaDmS0KAM0mV8wVmmdc:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 28 at r3](https://reviewable.io:443/reviews/toktok/website/34#-KaDm_9cgHZWcqBrm_Nt:-KaDm_9cgHZWcqBrm_Nu:b-wnlakj) ([raw file](https://github.com/toktok/website/blob/7e0c2790d9143b359c1797a8b063b3bfa83f0864/Makefile#L28)):*
> ```Makefile
> 
> spec: toktok/spec.md
> toktok/spec.md: hs-toxcore
> ```

Perhaps make it depend on `hs-toxcore $(shell find hs-toxcore -name "*.lhs" 2> /dev/null)`. This way, once hs-toxcore is cloned, it will depend on the doc files inside. The `2> /dev/null` avoids displaying the error of hs-toxcore not existing the first time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by cebe** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 28 at r3](https://reviewable.io:443/reviews/toktok/website/34#-KaDm_9cgHZWcqBrm_Nt:-KaEa3spdBs8EMnTWIwq:b-896fix) ([raw file](https://github.com/toktok/website/blob/7e0c2790d9143b359c1797a8b063b3bfa83f0864/Makefile#L28)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Perhaps make it depend on `hs-toxcore $(shell find hs-toxcore -name "*.lhs" 2> /dev/null)`. This way, once hs-toxcore is cloned, it will depend on the doc files inside. The `2> /dev/null` avoids displaying the error of hs-toxcore not existing the first time.
</blockquote></details>

Done.

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/toktok/website/34#-KaBVM0F2wYDjIMK6B97:-KaEa7wuzeoZaLBYHs68:b-896fix) ([raw file](https://github.com/toktok/website/blob/c654ca73b8cce95e8ea7c69a373c907488b5b316/README.md#L10)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

so better remove it again?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 6 of 11 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34#-:-KaEjS5EYddZUumaVaSe:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/34)*

**Pull request merged**
