### PR TITLE
Make reviewers column more readable in pr-table.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/19)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/pulls.html, line 61 at r1](https://reviewable.io:443/reviews/toktok/website/19#-Ka22ho1LeJdRj9QUH3a:-Ka22ho1LeJdRj9QUH3b:bmu1ub3) ([raw file](https://github.com/toktok/website/blob/31db26ea9f2afd59c057fae2ae667f07fb683fd6/toktok/pulls.html#L61)):*
> ```HTML
>             "<td>" + json[i][j].prTitle      + "</td>" +
>             "<td>" + stateIcon[json[i][j].prState] + "</td>" +
>             "<td>" + json[i][j].prReviewers.toString().replace(/,/g , ", ") + "</td>";
> ```

`.join(", ")` does the same thing, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19)*

**Comment by robinlinden** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[toktok/pulls.html, line 61 at r1](https://reviewable.io:443/reviews/toktok/website/19#-Ka22ho1LeJdRj9QUH3a:-Ka2LTCe1j8dODhH9Eyb:b-xvohb6) ([raw file](https://github.com/toktok/website/blob/31db26ea9f2afd59c057fae2ae667f07fb683fd6/toktok/pulls.html#L61)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`.join(", ")` does the same thing, right?
</blockquote></details>

You're right. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19#-:-Ka2LzWSA_73M28aNUJJ:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/19#-:-Ka2RjmpaPxaWx81x0KP:b-jbsf8z)*

**Pull request merged**
