### PR TITLE
use twemoij.js to enable emoij in all browsers

### LINKED ISSUE #14: wrong icons on the pull table
2017-01-08-230709_679x122_scrot

### PR DESCRIPTION
**Pull request by cebe**
- https://github.com/twitter/twemoji
- a makefile greps all used emoijs from the markup files and
  downloads the relevant emoij images from github. Cloning the repo
  would be overkill as it is > 500MB.

fixes #14

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/website/22)

### CODE REVIEW

**Comment by iphydf** [comment]
Do we need to replicate the emojis in our repo, if we can just download them on page build?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 25 at r1](https://reviewable.io:443/reviews/toktok/website/22#-Ka24EcynA9UBW9WWir8:-Ka24EcynA9UBW9WWir9:b-chmy8e) ([raw file](https://github.com/toktok/website/blob/bc39b638f82b370f658a3207c8fa7496f070eeab/Makefile#L25)):*
> ```Makefile
> emoij:
> 	mkdir -p toktok/static/img/emoij/16x16
> 	for codepoint in $$(grep -Prhio '&#x[\da-f]+;' toktok/ | grep -ioP '[\da-f]+'); do \
> ```

You can use `make` to parallelise this loop for you.

---

*[Makefile, line 27 at r1](https://reviewable.io:443/reviews/toktok/website/22#-Ka23YJNqHUlwg42wlbE:-Ka23YJNqHUlwg42wlbF:b-1l1f77) ([raw file](https://github.com/toktok/website/blob/bc39b638f82b370f658a3207c8fa7496f070eeab/Makefile#L27)):*
> ```Makefile
> 	for codepoint in $$(grep -Prhio '&#x[\da-f]+;' toktok/ | grep -ioP '[\da-f]+'); do \
> 		echo $$codepoint; \
> 		wget https://raw.githubusercontent.com/twitter/twemoji/gh-pages/16x16/$$codepoint.png -O toktok/static/img/emoij/16x16/$${codepoint}.png ; \
> ```

Add `|| exit 1` after the wget command so that it fails when one of the emojis can't be downloaded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22#-:-Ka245fiwTSBeXRdIBBx:b-96hpnn)*

**Comment by cebe** [comment]
actually, no need to. I can change that.

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Makefile, line 25 at r1](https://reviewable.io:443/reviews/toktok/website/22#-Ka24EcynA9UBW9WWir8:-Ka25LZ5jv-NL-5jWuuq:b-mu3u0j) ([raw file](https://github.com/toktok/website/blob/bc39b638f82b370f658a3207c8fa7496f070eeab/Makefile#L25)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

You can use `make` to parallelise this loop for you.
</blockquote></details>

I know but I am lazy and that worked :) changed it.

---

*[Makefile, line 27 at r1](https://reviewable.io:443/reviews/toktok/website/22#-Ka23YJNqHUlwg42wlbE:-Ka2I78KFo_6rlhFE5Ea:bye7ayf) ([raw file](https://github.com/toktok/website/blob/bc39b638f82b370f658a3207c8fa7496f070eeab/Makefile#L27)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Add `|| exit 1` after the wget command so that it fails when one of the emojis can't be downloaded.
</blockquote></details>

fixed with the new way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22#-:-Ka258iQCK7B7SqTw1a-:b-qe6hli)*

**Comment by iphydf** [comment]
Reviewed 2 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 25 at r1](https://reviewable.io:443/reviews/toktok/website/22#-Ka24EcynA9UBW9WWir8:-Ka2RYNt5aYJqF99L9IN:b-st13u7) ([raw file](https://github.com/toktok/website/blob/bc39b638f82b370f658a3207c8fa7496f070eeab/Makefile#L25)):*
<details><summary><i>Previously, cebe (Carsten Brandt) wrote…</i></summary><blockquote>

I know but I am lazy and that worked :) changed it.
</blockquote></details>

Cool, that's exactly what I wanted :) thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22#-:-Ka2RcbnctozwHvXS4nS:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 3 of 9 files at r1, 2 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22#-:-Ka2d2eLDWGrvOv0PAi-:b-jbsf8z)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Comment by robinlinden** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/website/22)*

**Pull request merged**
